### ISSUE TITLE
pip install fail using distributed wheel

### ISSUE THREAD

**Issue by SMEAC** [NVIDIA/trt-llm-rag-windows#104]
After clean installation of Python 3.10 (IAW Readme) and microsoft MPI (Both exe and msi), the wheel install in the ChatRTX readme fails with the following result:

pip install .\tensorrt_llm-0.9.0-cp310-cp310-win_amd64.whl

Processing c:\users\username\chatrtx\chatrtx_apis\dist\tensorrt_llm-0.9.0-cp310-cp310-win_amd64.whl
Collecting accelerate==0.25.0 (from tensorrt-llm==0.9.0)
  Downloading accelerate-0.25.0-py3-none-any.whl.metadata (18 kB)
Collecting build (from tensorrt-llm==0.9.0)
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Collecting colored (from tensorrt-llm==0.9.0)
  Downloading colored-2.2.4-py3-none-any.whl.metadata (3.6 kB)
Collecting cuda-python==12.3.0 (from tensorrt-llm==0.9.0)
  Downloading cuda_python-12.3.0-cp310-cp310-win_amd64.whl.metadata (12 kB)
Collecting diffusers==0.15.0 (from tensorrt-llm==0.9.0)
  Downloading diffusers-0.15.0-py3-none-any.whl.metadata (19 kB)
Collecting mpi4py (from tensorrt-llm==0.9.0)
  Downloading mpi4py-4.0.1-cp310-cp310-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: numpy in c:\users\username\.conda\envs\chatrtx_wheel\lib\site-packages (from tensorrt-llm==0.9.0) (1.26.4)
Collecting onnx>=1.12.0 (from tensorrt-llm==0.9.0)
  Downloading onnx-1.17.0-cp310-cp310-win_amd64.whl.metadata (16 kB)
Collecting polygraphy (from tensorrt-llm==0.9.0)
  Downloading polygraphy-0.49.9-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: psutil in c:\users\username\.conda\envs\chatrtx_wheel\lib\site-packages (from tensorrt-llm==0.9.0) (6.1.0)
Collecting pynvml>=11.5.0 (from tensorrt-llm==0.9.0)
  Using cached pynvml-12.0.0-py3-none-any.whl.metadata (5.4 kB)
Collecting pulp (from tensorrt-llm==0.9.0)
  Downloading PuLP-2.9.0-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: pandas in c:\users\username\.conda\envs\chatrtx_wheel\lib\site-packages (from tensorrt-llm==0.9.0) (2.2.3)
Collecting h5py==3.10.0 (from tensorrt-llm==0.9.0)
  Downloading h5py-3.10.0-cp310-cp310-win_amd64.whl.metadata (2.5 kB)
Requirement already satisfied: pywin32 in c:\users\username\.conda\envs\chatrtx_wheel\lib\site-packages (from tensorrt-llm==0.9.0) (307)
Collecting StrEnum (from tensorrt-llm==0.9.0)
  Downloading StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
Collecting sentencepiece>=0.1.99 (from tensorrt-llm==0.9.0)
  Downloading sentencepiece-0.2.0-cp310-cp310-win_amd64.whl.metadata (8.3 kB)
Collecting tensorrt==9.3.0.post12.dev1 (from tensorrt-llm==0.9.0)
  Downloading tensorrt-9.3.0.post12.dev1.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\username\AppData\Local\Temp\pip-install-vzv5ea77\tensorrt_942bfa822e034e229343ebe22e7485f4\setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by SMEAC** [comment]
Cut paste had failed to pick up extra url link.
Works.
