### ISSUE TITLE
I had to install Microsoft MPI to be able to run it otherwise it was throwing error

### ISSUE THREAD

**Issue by SoniCoder** [NVIDIA/trt-llm-rag-windows#29]
Installed it from here: https://www.microsoft.com/en-us/download/details.aspx?id=105289

Here's the error I was getting:

Traceback (most recent call last):
  File "C:\Users\Phoenix\AppData\Local\NVIDIA\ChatWithRTX\RAG\trt-llm-rag-windows-main\app.py", line 101, in <module>
    llm = TrtLlmAPI(
  File "C:\Users\Phoenix\AppData\Local\NVIDIA\ChatWithRTX\RAG\trt-llm-rag-windows-main\trt_llama_api.py", line 106, in __init__
    runtime_rank = tensorrt_llm.mpi_rank()
  File "C:\Users\Phoenix\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\tensorrt_llm\_utils.py", line 221, in mpi_rank
    return mpi_comm().Get_rank()
  File "C:\Users\Phoenix\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\tensorrt_llm\_utils.py", line 216, in mpi_comm
    from mpi4py import MPI
ImportError: DLL load failed while importing MPI: The specified module could not be found.

**Comment by kedarpotdar-nv** [comment]
Hi @SoniCoder , thanks for reporting. Yes, MPI is a pre-requisite for TensorRT-LLM. We will make it clearer in the install instructions.
