### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by okbckim** [NVIDIA/trt-llm-rag-windows#47]
I clean-installed this program and got this error message when I run the program. Any idea?

App running with config
 {
    "models": {
        "supported": [
            {
                "name": "Mistral 7B int4",
                "installed": true,
                "metadata": {
                    "model_path": "model\\mistral\\mistral7b_int4_engine",
                    "engine": "llama_float16_tp1_rank0.engine",
                    "tokenizer_path": "model\\mistral\\mistral7b_hf",
                    "max_new_tokens": 1024,
                    "max_input_token": 7168,
                    "temperature": 0.1
                }
            },
            {
                "name": "Llama 2 13B int4",
                "installed": true,
                "metadata": {
                    "model_path": "model\\llama\\llama13_int4_engine",
                    "engine": "llama_float16_tp1_rank0.engine",
                    "tokenizer_path": "model\\llama\\llama13_hf",
                    "max_new_tokens": 1024,
                    "max_input_token": 3900,
                    "temperature": 0.1
                }
            }
        ],
        "selected": "Mistral 7B int4"
    },
    "sample_questions": [
        {
            "query": "How does NVIDIA ACE generate emotional responses?"
        },
        {
            "query": "What is Portal prelude RTX?"
        },
        {
            "query": "What is important about Half Life 2 RTX?"
        },
        {
            "query": "When is the launch date for Ratchet & Clank: Rift Apart on PC?"
        }
    ],
    "dataset": {
        "sources": [
            "directory",
            "youtube",
            "nodataset"
        ],
        "selected": "directory",
        "path": "dataset",
        "isRelative": true
    },
    "strings": {
        "directory": "Folder Path",
        "youtube": "YouTube URL",
        "nodataset": "AI model default"
    }
}
Traceback (most recent call last):
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\RAG\trt-llm-rag-windows-main\app.py", line 114, in <module>
    embed_model = HuggingFaceEmbeddings(model_name=embedded_model)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\langchain\embeddings\huggingface.py", line 66, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\sentence_transformers\util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\huggingface_hub\hf_api.py", line 2219, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\bckim\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)), '(Request ID: c6321ef8-fa49-48f6-b52c-f68f29a3d51c)')
Press any key to continue . . .

**Comment by ajw1970** [comment]
I'm getting this same result which errors out at ssl.py too. 

`File "C:\Users\ajw1970\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\ssl.py", line 1375, in do_handshake
self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`

**Comment by anujj** [comment]
Can you please try the updated version release/0.3v.

**Comment by ajw1970** [comment]
> Can you please try the updated version release/0.3v.

Yes, this is working now on both the current "Final" version and the one before that.

**Comment by anujj** [comment]
thanks
