### ISSUE TITLE
already passed  the verify_install.py but cant pass the app.py  "ImportError: DLL load failed while importing tensorrt: 找不到指定的模块。"

### ISSUE THREAD

**Issue by beeinwind** [NVIDIA/trt-llm-rag-windows#63]
(ChatRTX) E:\chat1\trt-llm-rag-windows>python app.py
E:\chat1\ChatRTX\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "E:\chat1\trt-llm-rag-windows\app.py", line 31, in <module>
    from trt_llama_api import TrtLlmAPI
  File "E:\chat1\trt-llm-rag-windows\trt_llama_api.py", line 42, in <module>
    from utils import (DEFAULT_HF_MODEL_DIRS, DEFAULT_PROMPT_TEMPLATES,
  File "E:\chat1\trt-llm-rag-windows\utils.py", line 22, in <module>
    from tensorrt_llm.builder import get_engine_version
  File "E:\chat1\ChatRTX\lib\site-packages\tensorrt_llm\__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "E:\chat1\ChatRTX\lib\site-packages\tensorrt_llm\functional.py", line 26, in <module>
    import tensorrt as trt
  File "E:\chat1\ChatRTX\lib\site-packages\tensorrt\__init__.py", line 18, in <module>
    from tensorrt_bindings import *
  File "E:\chat1\ChatRTX\lib\site-packages\tensorrt_bindings\__init__.py", line 71, in <module>
    from .tensorrt import *
ImportError: DLL load failed while importing tensorrt: 找不到指定的模块。

**Comment by anujj** [comment]
@beeinwind: can you please share the pip freeze output,  i wanted to check if the trt-llm in installed correctly

**Comment by anujj** [comment]
@beeinwind Also did you install the Microsoft MIP as mentioned in the readme file ?
