### ISSUE TITLE
[BUG] "Invalid session." casued by "key, value = cookie.split('=')"

### ISSUE THREAD

**Issue by daxiongshu** [NVIDIA/trt-llm-rag-windows#71]
With ChatRTX 0.3, I have this error on windows 11 with A6000 GPUs.

On the browser, `https://127.0.0.1:46616`, the error message is:
```
Invalid session. Reopen ChatRTX from desktop to continue chatting.
```

On the terminal, the error message is 
```
Running on local URL:  https://127.0.0.1:46616

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\aixue\AppData\Local\NVIDIA\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.3\ui\user_interface.py", line 957, in _validate_session_and_raise
    self._validate_request(request)
  File "C:\Users\aixue\AppData\Local\NVIDIA\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.3\ui\user_interface.py", line 483, in _validate_request
    key, value = cookie.split('=')
ValueError: too many values to unpack (expected 2)

```

**Comment by anujj** [comment]
there will a another link in the cmd **with the cookie**. Please use that link to open in browser
