### ISSUE TITLE
Build the Mistral TRT-LLM int4 AWQ Engine not working

### ISSUE THREAD

**Issue by kzpromo** [NVIDIA/trt-llm-rag-windows#77]
(chatrtx) C:\chatrtx>trtllm-build --checkpoint_dir .\model\mistral_model\model_checkpoints --output_dir .\model\mistral_model\engine --gpt_attention_plugin float16 --gemm_plugin float16 --max_batch_size 1 --max_input_len 7168 --max_output_len 1024 --context_fmha=enable --paged_kv_cache=disable --remove_input_padding=disable
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\anaconda3\envs\chatrtx\lib\site-packages\tensorrt_llm\__init__.py", line 39, in <module>
    import tensorrt_llm.bindings  # NOQA
ImportError: DLL load failed while importing bindings: Не найден указанный модуль.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\anaconda3\envs\chatrtx\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\***\AppData\Local\anaconda3\envs\chatrtx\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\***\AppData\Local\anaconda3\envs\chatrtx\Scripts\trtllm-build.exe\__main__.py", line 4, in <module>
  File "C:\Users\***\AppData\Local\anaconda3\envs\chatrtx\lib\site-packages\tensorrt_llm\__init__.py", line 41, in <module>
    raise ImportError(
ImportError: Import of the `bindings` module failed. Please check the package integrity. If you are attempting to use the pip development mode (editable installation), please execute `build_wheels.py` first, and then run `pip install -e .`

**Comment by anujj** [comment]
This usually means that a dynamic dependency of the bindings library is missing on PATH. Can u please try with these command 

```
python -m pip uninstall -y tensorrt
pip uninstall -y tensorrt tensorrt_libs tensorrt_bindings
python -m pip install --pre --extra-index-url https://pypi.nvidia.com/ tensorrt==9.3.0.post12.dev1 --no-cache-dir
Check with: python -c "import tensorrt_llm; print(tensorrt_llm._utils.trt_version())"
```

**Comment by akaanupkumar** [comment]
Please verify pre-requisites and move to newly released 0.5 version. There is no such known issue in 0.5 version. let us know if you are facing issue on 0.5 version.
